# This file generates the GitHub Actions matrix
---
include:
  # rommana
  - board: seeeduino_xiao_ble
    shield: rommana_central_dongle dongle_display
    artifact-name: rommana_central_dongle
  - board: seeeduino_xiao_ble
    shield: rommana_central_left rgbled_adapter
    artifact-name: rommana_central_left
  - board: seeeduino_xiao_ble
    shield: rommana_peripheral_left rgbled_adapter
    artifact-name: rommana_peripheral_left
  - board: seeeduino_xiao_ble
    shield: rommana_peripheral_right rgbled_adapter
    artifact-name: rommana_peripheral_right
    
  - board: seeeduino_xiao_ble
    shield: rommana_central_dongle dongle_display
    snippet: zmk-usb-logging
    artifact-name: rommana_central_dongle_with_logging

  # sweep
  - board: seeeduino_xiao_ble
    shield: sweep_central_dongle dongle_display
    artifact-name: sweep_central_dongle
  - board: nice_nano_v2
    shield: sweep_central_left led_indicator
    artifact-name: sweep_central_left
  - board: nice_nano_v2
    shield: sweep_peripheral_left led_indicator
    artifact-name: sweep_peripheral_left
  - board: nice_nano_v2
    shield: sweep_peripheral_right led_indicator
    artifact-name: sweep_peripheral_right
    
  - board: nice_nano_v2
    shield: sweep_central_left led_indicator
    snippet: zmk-usb-logging
    artifact-name: sweep_central_left_with_logging

  # reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: nice_nano_v2
    shield: settings_reset
